### ISSUE TITLE
Seems to be down

### ISSUE THREAD

**Issue by AnoRebel** [alphaolomi/primelyrics#31]
I tried the app but it doesnt seem to go past the circular progressbar, checking the Dev tools, I see an XHR error, with 403 code. Might be the cors-anywhere problem, as its the one propagating the 403 to the Search.tsx page.

Great work btw.

**Comment by alphaolomi** [comment]
Hi @AnoRebel, 

I noticed it too, some problem with CORS

Am working rewriting(#21) to Typescript, 

I will get to it next (#32)

**Comment by AnoRebel** [comment]
Awesome, looking forward to it.. Again, great work.

**Comment by alphaolomi** [comment]
One of the services that was being used changed their  plans

CORS anywhere hosted at  https://github.com/Rob--W/cors-anywhere

see issue 301

Plan is host private cors-anywhere server

**Comment by AnoRebel** [comment]
Aah, yeah, you could do that with heroku's free hosting plan

**Comment by alphaolomi** [comment]
# Update 🥳 

App hosted at https://primelyrics.netlify.app/

Looking for more feature requests and ideas.

**Comment by AnoRebel** [comment]
Great, checking it out..

Will be updating for anything..

Keep the good work up..
